language: java
jdk:
  - openjdk8
  
env: 
  - JDK=openjdk8

dist: trusty
 
services:
  - mysql
before_script:
  - jdk_switcher use $JDK
  - cd stock_manager
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS  cinedb;'
  - mysql -u root -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';"
  - mysql -u root -e "GRANT ALL ON cinedb.* TO 'spq'@'localhost';"



addons:
  sonarcloud:
    organization: "markitos98"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=markitos98_ProcesosB_04
  
  after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn clean test jacoco:report coveralls:report

//prueba
