language: java
jdk:
    - openjdk8    
 
 
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE SCHEMA cinedb;'
  - mysql -u root -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';"
  - mysql -u root -e "GRANT ALL ON cinedb.* TO 'spq'@'localhost';"
      
    
addons:
  sonarcloud:
    organization: "markitos98"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn clean test jacoco:report coveralls:report

