language: java
os: linux
jdk:
    - openjdk8    
    
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE cinedb;'
  - mysql -u root -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';"
  - mysql -u root -e "GRANT ALL ON cinedb.* TO 'spq'@'localhost';"
      
    
script:
    - mvn test -DargLine="-Dcontiperf.active=false"


