/* DELETE 'cinedb' database*/
DROP SCHEMA IF EXISTS cinedb;
/* DELETE USER 'spq' AT LOCAL SERVER*/
DROP USER IF EXISTS 'spq'@'%';

/* CREATE 'cinedb' DATABASE */
CREATE SCHEMA cinedb;
/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD 'spq' */
CREATE USER IF NOT EXISTS 'spq'@'%' IDENTIFIED BY 'spq';

GRANT ALL ON cinedb.* TO 'spq'@'%';