name: Java ci
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:

   build:
     runs-on: ubuntu-latest

steps:

     - name: Instalar  JDK 15
        uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'   
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
      
        env:
          DB_DATABASE: cinedb
          DB_USER: 'spq'
          DB_PASSWORD: 'spq'
          DB_HOST: 'localhost'
        ports:
          - 3306:3306
     -name: Limpiar proyecto
        run: mvn clean
     -name: Compilar proyecto
        run: mvn compile
     -name: Enhance
        run: mvn datanucleus:enhance
     -name: Crear esquema
        run: mvn datanucleus:schema-create
     -name: Test
        run: mvn test
     -name: Test Integracion
        run: mvn exec:java -Pinte
     -name: Instalar doxygen
        run: sudo apt-get install -y doxygen
     -name: Generar documentacion
        run: mvn doxygen:report
     -name: validar
        run: mvn validate
     -name: Publicar en Github Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: target/doxygen/html
        env: ${{ secrets.GITHUB }}
