name: Java CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    

    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
  
      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots compile 
          mvn --batch-mode --update-snapshots datanucleus:enhance
          mvn --batch-mode --update-snapshots datanucleus:schema-create
          mvn --batch-mode --update-snapshots exec:java -P datos
      - name: Test Unitarios
        run: mvn --batch-mode --update-snapshots test 
      - name: Test Integracion
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < src/main/resources/database.sql
          mvn --batch-mode --update-snapshots exec:java -P datos
          mvn --batch-mode --update-snapshots verify -P integration

     - name: Install doxygen
      run: sudo apt-get install -y doxygen
    - name: Install graphviz
      run: sudo apt-get install -y graphviz
    - name: Test with Maven
      run: mvn test -DargLine="-Dcontiperf.active=false"
    - name: Generate documentation
      run: mvn doxygen:report
    - name: Publish on Github Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
       build_dir: target/doxygen/html
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
